theme: jekyll-theme-minimal
title: Priti Bhunia
description: pritibhunia@gmail.com
logo: docs/img3.jpg
url: https://pritibhunia.github.io/

# Site Author
author:
#  name             : "Your Sidebar Name"
#  avatar           : "profile.png"
#  bio              : "Your biography for the left-hand sidebar"
  location         : "Bangalore, India"
  linkedin         : "https://www.linkedin.com/in/pritibhunia"
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  twitter          : #"replacethistwitterhandle"
